# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: bot_mh50
  joint_model_group_pose: default_aims
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - r1_joint_1_s
    - r1_joint_2_l
    - r1_joint_3_u
    - r1_joint_4_r
    - r1_joint_5_b
    - r1_joint_6_t
    - r2_joint_s
    - r2_joint_l
    - r2_joint_u
    - r2_joint_r
    - r2_joint_b
    - r2_joint_t
    - r3_joint_1_s
    - r3_joint_2_l
    - r3_joint_3_u
    - r3_joint_4_r
    - r3_joint_5_b
    - r3_joint_6_t
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: bot_mh50_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r3_joint_1_s
      - r3_joint_2_l
      - r3_joint_3_u
      - r3_joint_4_r
      - r3_joint_5_b
      - r3_joint_6_t
  - name: bot_ms210_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r2_joint_s
      - r2_joint_l
      - r2_joint_u
      - r2_joint_r
      - r2_joint_b
      - r2_joint_t
  - name: bot_ma2010_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r1_joint_1_s
      - r1_joint_2_l
      - r1_joint_3_u
      - r1_joint_4_r
      - r1_joint_5_b
      - r1_joint_6_t