# Ordering from 0 to 2 is required due to real controller configuration.
# R1 - MA2010
# R2 - MS210
# R3 - MH50

topic_list:
    - name: wc1_r1_controller
      ns: wc1
      group: 0
      joints: ['r1_joint_1_s', 'r1_joint_2_l', 'r1_joint_3_u', 'r1_joint_4_r', 'r1_joint_5_b', 'r1_joint_6_t']
    - name: wc1_r2_controller
      ns: wc1
      group: 1
      joints: ['r2_joint_1_s', 'r2_joint_2_l', 'r2_joint_3_u', 'r2_joint_4_r', 'r2_joint_5_b', 'r2_joint_6_t']
    - name: wc1_r3_controller
      ns: wc1
      group: 2
      joints: ['r3_joint_1_s', 'r3_joint_2_l', 'r3_joint_3_u', 'r3_joint_4_r', 'r3_joint_5_b', 'r3_joint_6_t']
